services:
  pybackend:
    restart: always

    build:
      context: /backend/event_logic
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  gobackend:
    restart: always

    build:
      context: /backend/authorization
      dockerfile: Dockerfile
    ports:
      - 8080:8080